default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['APPNAME_DATABASE_USERNAME'] %> 
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %> 
  database: rails_react_calendar
  url: <%= ENV["DATABASE_URL"] %>

